version: "3.8"

services:
  xssmaze:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network

  waf:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "8080:8080"
    environment:
      - BACKEND=http://xssmaze:3000
      - PARANOIA=4  # higher paranoia levels are considered more aggressive and provide increased protection (1~4)
      - DEFAULT_ACTION=deny,status:403
    depends_on:
      - xssmaze
    networks:
      - app-network

networks:
  app-network:
    driver: bridge